// Generated by CoffeeScript 1.9.2
(function() {
  (function() {
    var HelloApp, Name;
    Name = ng.Component({
      selector: 'name',
      template: '<ul><li *ng-for="#name of names">{{name}}</li></ul>',
      directives: [ng.NgFor]
    }).Class({
      constructor: function() {
        return {
          names: ['Phil', 'George', 'Bob', 'Frank']
        };
      }
    });
    HelloApp = ng.Component({
      selector: 'hello-app',
      template: '<h1>Hello Ang 2</h1><name></name>',
      directives: [Name]
    }).Class({
      constructor: function() {
        return {
          name: 'Bob'
        };
      }
    });
    return document.addEventListener('DOMContentLoaded', function() {
      return ng.bootstrap(HelloApp);
    });
  })();

}).call(this);
